repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Pin to the latest ruff version
    rev: v0.4.4
    hooks:
    # Run the linter
    -   id: ruff
        args: [--fix]
    # Run the formatter
    -   id: ruff-format